substitutions:
  device_id: bed-room
  device_name: Bed Room
  platform: ESP8266
  board: nodemcuv2
  wifi_ssid: !secret wifi_ssid
  wifi_passwd: !secret wifi_passwd
  ota_pwd: !secret ota_pwd
  api_pwd: !secret api_pwd
  ap_wifi_pwd: !secret ap_wifi_pwd

<<: !include common/esphome.yaml
<<: !include common/common.yaml

i2c:
  - id: bmp
    sda: GPIO4
    scl: GPIO5
    scan: True

sensor:
  - platform: bmp280
    i2c_id: bmp
    temperature:
      name: "${device_name} Temperature"  
      oversampling: 1x
      accuracy_decimals: 2
      filters:
        - median:
            window_size: 10
            send_every: 5
            send_first_at: 5
        - offset: -3.0
    pressure:
      name: "${device_name} Pressure"      
      oversampling: 1x
      accuracy_decimals: 2
    address: 0x76
    update_interval: 60s
    iir_filter: 2x
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi.yaml

text_sensor:
  - !include common/text_sensor/version.yaml
  - !include common/text_sensor/wifi.yaml
