substitutions:
  device_id: vaillant-combi
  device_name: Vaillant Combi
  platform: ESP8266
  board: d1_mini
  wifi_ssid: !secret wifi_ssid
  wifi_passwd: !secret wifi_passwd
  ota_pwd: !secret ota_pwd
  api_pwd: !secret api_pwd
  ap_wifi_pwd: !secret ap_wifi_pwd


<<: !include common/esphome.yaml
<<: !include common/common.yaml

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_passwd}
  reboot_timeout: 5min
  output_power: 20.5dB
  power_save_mode: none
  ap:
    ssid: ${device_id}
    password: ${ap_wifi_pwd}

sensor:
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi.yaml


text_sensor:
  - !include common/text_sensor/version.yaml
  - !include common/text_sensor/wifi.yaml

switch:
  - platform: gpio
    pin:
      number: D1
      mode: OUTPUT
    name: "${device_name} Status"
    restore_mode: ALWAYS_OFF
